# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a24ef5f16006398656570dc47aa2ce51c891555df5d33a55c9d57b11eaffa20559eba8e612c06354213f5aef07feb13dd5fc0f20cbbc3bd80fedb1b6b713bb8

test:
  secret_key_base: 7ff97ed6f3b8d655e889c0d2550cc6fd1b411da817e1600a4a9462b1d504ef8c0699946db0e4087dc2a523caf659618b9e1d264253082e5fdfe543f9d34d50fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
